{
  "openapi": "3.0.1",
  "info": {
    "title": "Open API ONCall v3 Externals",
    "description": "Open API for ONCall and Mechanical cases.",
    "version": "2025-08-12T17:37:48.000Z"
  },
  "servers": [
    {
      "url": "https://qualif.api.michelin.com"
    },
    {
      "url": "https://api.michelin.com"
    }
  ],
  "security": [
    {
      "bearer": []
    }
  ],
  "paths": {
    "/amn/moc/v3/cases/{id}": {
      "get": {
        "tags": [
          "Cases"
        ],
        "description": "Get unified case (v3)",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Unified case number",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Case details",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "created_at": "2025-07-27T20:11:52.211Z",
                    "updated_at": "2025-08-03T19:24:02.776Z",
                    "customerST": "1471852",
                    "customerBT": "1424651",
                    "id": "Z8D13493LK",
                    "ersResponse": {
                      "data": {
                        "assetLocation": {
                          "address": "202 GSP Logistic Parkway",
                          "city": "Greer",
                          "country": "USA",
                          "note": "comment",
                          "state": "SC",
                          "latitude": 34.9289684,
                          "longitude": -82.2007266,
                          "zipCode": "29651",
                          "highway": null,
                          "milemarker": null,
                          "timezone": null
                        },
                        "etaDuration": {
                          "min": null,
                          "max": null
                        },
                        "fixpix": {
                          "sent": "not_attempted",
                          "sentTimestamp": ""
                        },
                        "caseNumber": "E484128",
                        "caseStatus": "new",
                        "previousStatus": null,
                        "statusTimeStamp": "2025-07-27T20:11:59.712Z",
                        "userName": "maestro@michelin.com",
                        "typeOfCase": "api-call",
                        "inboundProgram": "Michelin OnCall - Electronic Dispatch",
                        "inboundProgramNumberId": 229,
                        "inboundCallerStore": null,
                        "inboundStoreBillTo": "NA",
                        "inboundStoreShipTo": null,
                        "paymentMethod": "michelin_line_of_credit",
                        "customerName": "HUB GROUP TRUCKING, INC. (ERS)",
                        "accountNumber": "1471852",
                        "providerName": null,
                        "poNumber": "888889",
                        "drNumber": "DR123204909",
                        "refNumber": "ref12345",
                        "ticketNumber": "DR123204909",
                        "invoiceNumber": "345",
                        "billingAmount": "0.00",
                        "workOrderNumber": null,
                        "billingComment": "test",
                        "releaseNumber": null,
                        "contractNumber": null,
                        "servicingDealerBilltoName": null,
                        "servicingDealerStore": null,
                        "servicingDealerTimezone": null,
                        "specialInstructions": "test patch",
                        "delayedService": true,
                        "delayedServiceNote": null,
                        "delayedServiceCompletionDate": "2025-07-26T00:00:00.000Z",
                        "delayedServiceDispatchDate": null,
                        "updatedAt": "2025-08-03T19:23:54.518Z",
                        "insertedAt": "2025-07-27T20:11:59.712Z",
                        "billable": false,
                        "customer": {
                          "shipTo": "1471852",
                          "billTo": "1424651",
                          "name": "HUB GROUP TRUCKING, INC. (ERS)",
                          "city": "OAK BROOK",
                          "state": "IL",
                          "zip": "60523",
                          "street": "2000 CLEARWATER DR"
                        },
                        "contacts": [
                          {
                            "contactName": "John",
                            "contactPhone": "+19314090552",
                            "contactType": "dispatch",
                            "contactEmail": null,
                            "callbackEta": false,
                            "callbackRolltime": false
                          },
                          {
                            "contactName": "John",
                            "contactPhone": "+19314090552",
                            "contactType": "driver_cell",
                            "contactEmail": null,
                            "callbackEta": false,
                            "callbackRolltime": false
                          }
                        ],
                        "serviceData": [],
                        "requestedService": [
                          {
                            "type": "request",
                            "unitNumber": "MT2626",
                            "action": "replace",
                            "condition": "blank_case",
                            "position": "rf",
                            "axle": "other",
                            "tireSize": "10.00/90R20",
                            "tireBrand": "Michelin",
                            "treadDesign": "PILOT XFA",
                            "productType": "New",
                            "rimMaterial": null,
                            "wheelOffset": null,
                            "rimType": null,
                            "loadRange": "see_notes",
                            "confirmed": null
                          }
                        ],
                        "agreedService": [
                          {
                            "type": "agreement",
                            "unitNumber": "MT2626",
                            "action": "replace",
                            "condition": "blank_case",
                            "position": "rf",
                            "axle": "other",
                            "tireSize": "10.00/90R20",
                            "tireBrand": "Michelin",
                            "treadDesign": "PILOT XFA",
                            "productType": "New",
                            "rimMaterial": null,
                            "wheelOffset": null,
                            "rimType": null,
                            "loadRange": "see_notes",
                            "confirmed": null
                          }
                        ],
                        "suppliedService": [
                          {
                            "type": "supplied",
                            "unitNumber": "MT2626",
                            "action": "replace",
                            "condition": "blank_case",
                            "position": "rf",
                            "axle": "other",
                            "tireSize": "10.00/90R20",
                            "tireBrand": "Michelin",
                            "treadDesign": "PILOT XFA",
                            "productType": "New",
                            "rimMaterial": null,
                            "wheelOffset": null,
                            "rimType": null,
                            "loadRange": "see_notes",
                            "confirmed": true
                          }
                        ],
                        "caseNotes": [],
                        "linkedCalls": [],
                        "notifications": [],
                        "assets": [
                          {
                            "identifier": "d7ec109b-ac3d-49b6-bb6e-32bcee4364aa",
                            "unitNumber": "MT2626",
                            "unitType": "tractor",
                            "vin": null
                          }
                        ],
                        "customerProfile": {
                          "fleetContactsAvailable": true,
                          "driverAuthorized": null,
                          "poRequired": false,
                          "tirePreferences": true,
                          "wheelPreferences": false,
                          "emailPreferences": true
                        },
                        "caseStatusChanges": [],
                        "delays": []
                      },
                      "codeResponse": 200
                    },
                    "mechanicalResponse": {
                      "data": {
                        "eventNumber": 8837388,
                        "custId": 119758,
                        "customerCode": "MOCKN46",
                        "customerPONumber": "888889",
                        "createDateUtc": "2025-07-27T03:54:22.937Z",
                        "updatedDateUtc": "2025-08-03T20:27:19.75Z",
                        "vendorAssignedDateUtc": "2025-07-27T04:20:00Z",
                        "repairStartedDateUtc": "2025-07-27T06:30:00Z",
                        "repairCompletedDateUtc": "2025-07-27T10:07:00Z",
                        "serviceProviderWorkCompletedDateUtc": null,
                        "status": "rolling"
                      },
                      "codeResponse": 200
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Cases"
        ],
        "description": "Allows to update the case information (billing information, assets, products, location, etc).",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Case Number",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "billingInfo": {
                    "comment": "Send any comment here",
                    "poNumber": "Po Number here",
                    "drNumber": "DR Number here",
                    "referenceNumber": "reference number here",
                    "invoiceNumber": "invoice number here",
                    "amount": "0.00"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": "Case update",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "id": "Z8D13493LK",
                    "customerST": "1471852",
                    "customerBT": "1424651",
                    "created_at": "2025-07-27T20:11:52.211Z",
                    "updated_at": "2025-08-03T19:24:02.776Z",
                    "ersResponse": {
                      "codeResponse": 200,
                      "data": {
                        "id": "E484128",
                        "inboundProgramNumberId": "229",
                        "status": "NEW",
                        "dispatchedAt": null,
                        "billTo": null,
                        "shipTo": null,
                        "eta": null,
                        "provider": {
                          "name": null,
                          "address": null
                        },
                        "source": "OnCall",
                        "parent_company": null,
                        "home_office": null
                      }
                    },
                    "mechanicalResponse": {
                      "codeResponse": 200,
                      "data": {
                        "eventNumber": 8837388,
                        "custId": 119758,
                        "customerCode": "MOCKN46",
                        "customerPONumber": "888889",
                        "createDateUtc": "2025-07-27T03:54:22.937Z",
                        "updatedDateUtc": "2025-08-03T20:27:19.75Z",
                        "vendorAssignedDateUtc": "2025-07-27T04:20:00Z",
                        "repairStartedDateUtc": "2025-07-27T06:30:00Z",
                        "repairCompletedDateUtc": "2025-07-27T10:07:00Z",
                        "serviceProviderWorkCompletedDateUtc": null,
                        "status": "new"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-codegen-request-body-name": "body"
      }
    },
    "/amn/moc/v3/cases": {
      "post": {
        "tags": [
          "Cases"
        ],
        "description": "Create a case in ONCall ERS system V3.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "location",
                  "fleet",
                  "assets",
                  "products",
                  "caller"
                ],
                "properties": {
                  "inboundProgramNumberId": {
                    "type": "string"
                  },
                  "location": {
                    "type": "object",
                    "required": [
                      "latitude",
                      "longitude",
                      "country",
                      "comments"
                    ],
                    "properties": {
                      "latitude": {
                        "type": "string"
                      },
                      "longitude": {
                        "type": "string"
                      },
                      "country": {
                        "type": "string"
                      },
                      "comments": {
                        "type": "string"
                      },
                      "highway": {
                        "type": "string",
                        "nullable": true
                      },
                      "mileMarker": {
                        "type": "string",
                        "nullable": true
                      },
                      "timezone": {
                        "type": "string",
                        "nullable": true
                      }
                    }
                  },
                  "fleet": {
                    "type": "object",
                    "required": [
                      "shipTo"
                    ],
                    "properties": {
                      "shipTo": {
                        "type": "string"
                      },
                      "billTo": {
                        "type": "string"
                      }
                    }
                  },
                  "domicile": {
                    "type": "string"
                  },
                  "assets": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "required": [
                        "vinNumber",
                        "unitDetail",
                        "unitPrimary",
                        "unitNumber",
                        "type",
                        "droppedUnit"
                      ],
                      "properties": {
                        "vinNumber": {
                          "type": "string"
                        },
                        "unitDetail": {
                          "type": "object",
                          "properties": {
                            "loadWeightInImperialPounds": {
                              "type": "number"
                            },
                            "mileage": {
                              "type": "number"
                            },
                            "hubReading": {
                              "type": "number"
                            },
                            "licensePlateNumber": {
                              "type": "string"
                            },
                            "unitYear": {
                              "type": "number"
                            },
                            "makeId": {
                              "type": "number"
                            },
                            "model": {
                              "type": "string"
                            }
                          }
                        },
                        "unitPrimary": {
                          "type": "boolean"
                        },
                        "unitNumber": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "droppedUnit": {
                          "type": "boolean"
                        }
                      }
                    }
                  },
                  "specialInstructions": {
                    "type": "string"
                  },
                  "products": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "required": [
                        "type",
                        "unitNumber"
                      ],
                      "properties": {
                        "type": {
                          "type": "string",
                          "enum": [
                            "TIRE",
                            "WHEEL",
                            "MECHANICAL"
                          ]
                        },
                        "unitNumber": {
                          "type": "string"
                        },
                        "tire": {
                          "type": "object",
                          "properties": {
                            "action": {
                              "type": "string"
                            },
                            "position": {
                              "type": "string"
                            },
                            "condition": {
                              "type": "string"
                            },
                            "axle": {
                              "type": "string"
                            },
                            "brand": {
                              "type": "string"
                            },
                            "type": {
                              "type": "string"
                            },
                            "tread": {
                              "type": "string"
                            },
                            "size": {
                              "type": "string"
                            },
                            "loadRange": {
                              "type": "string"
                            }
                          }
                        },
                        "wheel": {
                          "type": "object",
                          "properties": {
                            "position": {
                              "type": "string"
                            },
                            "size": {
                              "type": "string"
                            },
                            "offset": {
                              "type": "string"
                            },
                            "axle": {
                              "type": "string"
                            },
                            "material": {
                              "type": "string"
                            },
                            "type": {
                              "type": "string"
                            }
                          }
                        },
                        "mechanical": {
                          "type": "object",
                          "properties": {
                            "troubleCodeId": {
                              "type": "number"
                            },
                            "complaint": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    }
                  },
                  "caller": {
                    "type": "object",
                    "required": [
                      "phone",
                      "name"
                    ],
                    "properties": {
                      "phone": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "smsNotification": {
                        "type": "boolean",
                        "nullable": true
                      }
                    }
                  },
                  "driver": {
                    "type": "object",
                    "properties": {
                      "phone": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "smsNotification": {
                        "type": "boolean",
                        "nullable": true
                      }
                    }
                  },
                  "billingInfo": {
                    "type": "object",
                    "properties": {
                      "comment": {
                        "type": "string"
                      },
                      "poNumber": {
                        "type": "string"
                      },
                      "drNumber": {
                        "type": "string"
                      },
                      "referenceNumber": {
                        "type": "string"
                      },
                      "invoiceNumber": {
                        "type": "string"
                      },
                      "amount": {
                        "type": "string"
                      }
                    }
                  },
                  "delayedServiceCompletionDate": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "locationValidated": {
                    "type": "boolean",
                    "description": "Indicates if the vehicle location was validated by a device on the placement"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Case created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "customerST": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "updated_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "ersResponse": {
                      "type": "object",
                      "properties": {
                        "codeResponse": {
                          "type": "integer",
                          "description": "Response code from ERS system"
                        },
                        "data": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string"
                            },
                            "status": {
                              "type": "string",
                              "enum": [
                                "NEW",
                                "DISPATCHED",
                                "COMPLETED"
                              ]
                            },
                            "dispatchedAt": {
                              "type": "string",
                              "format": "date-time",
                              "nullable": true
                            },
                            "billTo": {
                              "type": "string",
                              "nullable": true
                            },
                            "shipTo": {
                              "type": "string",
                              "nullable": true
                            },
                            "eta": {
                              "type": "object",
                              "nullable": true,
                              "properties": {
                                "minMinutes": {
                                  "type": "string"
                                },
                                "maxMinutes": {
                                  "type": "string"
                                }
                              }
                            },
                            "source": {
                              "type": "string",
                              "nullable": true
                            }
                          }
                        },
                        "errors": {
                          "type": "object",
                          "additionalProperties": true,
                          "description": "Error messages from ERS system"
                        }
                      }
                    },
                    "mechanicalResponse": {
                      "type": "object",
                      "properties": {
                        "codeResponse": {
                          "type": "integer",
                          "description": "Response code from Mechanical system"
                        },
                        "data": {
                          "type": "object",
                          "properties": {
                            "eventNumber": {
                              "type": "number",
                              "description": "Event number from mechanical system"
                            },
                            "custId": {
                              "type": "number",
                              "description": "Customer ID"
                            },
                            "customerCode": {
                              "type": "string",
                              "description": "Customer code"
                            },
                            "customerPONumber": {
                              "type": "string",
                              "description": "Customer PO number"
                            },
                            "createDateUtc": {
                              "type": "string",
                              "format": "date-time",
                              "description": "Creation date in UTC"
                            },
                            "updatedDateUtc": {
                              "type": "string",
                              "format": "date-time",
                              "description": "Last update date in UTC"
                            },
                            "vendorAssignedDateUtc": {
                              "type": "string",
                              "format": "date-time",
                              "description": "Vendor assignment date in UTC"
                            },
                            "repairStartedDateUtc": {
                              "type": "string",
                              "format": "date-time",
                              "description": "Repair start date in UTC"
                            },
                            "repairCompletedDateUtc": {
                              "type": "string",
                              "format": "date-time",
                              "description": "Repair completion date in UTC"
                            },
                            "serviceProviderWorkCompletedDateUtc": {
                              "type": "string",
                              "format": "date-time",
                              "description": "Service provider work completion date in UTC"
                            }
                          }
                        },
                        "errors": {
                          "type": "object",
                          "properties": {
                            "errors": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "array",
                                "items": {
                                  "type": "string"
                                }
                              },
                              "description": "Error messages mapping"
                            },
                            "type": {
                              "type": "string",
                              "description": "Error type"
                            },
                            "title": {
                              "type": "string",
                              "description": "Error title"
                            },
                            "status": {
                              "type": "number",
                              "description": "Error status code"
                            },
                            "detail": {
                              "type": "string",
                              "description": "Detailed error message"
                            },
                            "instance": {
                              "type": "string",
                              "description": "Error instance identifier"
                            }
                          },
                          "additionalProperties": true,
                          "description": "Error details from mechanical system"
                        }
                      }
                    }
                  },
                  "required": [
                    "id",
                    "customerST",
                    "created_at",
                    "updated_at"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "object",
                      "additionalProperties": true
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Cases"
        ],
        "description": "Find cases. Either customerShipTo or customerBillTo (or both) must be provided.",
        "parameters": [
          {
            "name": "startDate",
            "in": "query",
            "description": "Start date in UTC format (ISO 8601). Example: 2025-08-13T00:00:00Z",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date-time",
              "example": "2025-08-13T00:00:00Z"
            }
          },
          {
            "name": "endDate",
            "in": "query",
            "description": "End date in UTC format (ISO 8601). Example: 2025-08-13T23:59:59Z",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date-time",
              "example": "2025-08-13T23:59:59Z"
            }
          },
          {
            "name": "customerShipTo",
            "in": "query",
            "description": "Customer Ship To. Either this or customerBillTo must be provided.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "customerBillTo",
            "in": "query",
            "description": "Customer Bill To. Either this or customerShipTo must be provided.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Pagination limit",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "skip",
            "in": "query",
            "description": "Pagination skip",
            "required": false,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of cases",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "cases": [
                      {
                        "id": 42,
                        "caseId": "I3BE6AINGC",
                        "ipn": null,
                        "customerShipTo": "1471852",
                        "ocxId": "E484103",
                        "fntId": null,
                        "fntCase": null,
                        "ocxCase": {
                          "data": {
                            "type": "ers-cases",
                            "warning": null,
                            "attributes": {
                              "contacts": [
                                {
                                  "name": "John",
                                  "type": "DRIVER_CELL",
                                  "phone": "9314090552",
                                  "callBackEta": false,
                                  "smsNotification": true,
                                  "callBackRollTime": false
                                },
                                {
                                  "name": "John",
                                  "type": "DISPATCH",
                                  "phone": "9314090552",
                                  "callBackEta": false,
                                  "smsNotification": true,
                                  "callBackRollTime": false
                                }
                              ],
                              "location": {
                                "zip": "29651",
                                "city": "Greer",
                                "note": "comment",
                                "state": "SC",
                                "country": "USA",
                                "highway": "",
                                "latitude": "34.9289684",
                                "timezone": "",
                                "longitude": "-82.2007266",
                                "mileMarker": "",
                                "searchValue": "202 GSP Logistic Parkway Greer, SC 29651 US",
                                "streetAddress": "202 GSP Logistic Parkway"
                              },
                              "agreedTires": [
                                {
                                  "asset": "#/data/attributes/primaryAsset",
                                  "axleType": "OTHER",
                                  "tireSize": "10.00/90R20",
                                  "loadRange": "L",
                                  "productType": "New",
                                  "manufacturer": "Michelin",
                                  "tirePosition": "RF",
                                  "requestedTire": "#/data/attributes/requestedTires/0",
                                  "tireCondition": "BLANK_CASE",
                                  "requestedAction": "REPLACE",
                                  "sculptedTreadName": "PILOT XFA"
                                }
                              ],
                              "billingInfo": {
                                "amount": "0.00",
                                "comment": "test",
                                "drNumber": "DR123204909",
                                "poNumber": "123",
                                "ticketNumber": "DR123204909",
                                "invoiceNumber": "345",
                                "referenceNumber": "ref12345"
                              },
                              "nafaCustomer": {
                                "billTo": "1424651",
                                "shipTo": "1471852"
                              },
                              "primaryAsset": {
                                "vin": null,
                                "type": "Tractor",
                                "unitNumber": "MT2626",
                                "droppedUnit": false
                              },
                              "relatedAssets": [],
                              "suppliedTires": [
                                {
                                  "asset": "#/data/attributes/primaryAsset",
                                  "axleType": "OTHER",
                                  "tireSize": "10.00/90R20",
                                  "loadRange": "L",
                                  "agreedTire": "#/data/attributes/agreedTires/0",
                                  "productType": "New",
                                  "manufacturer": "Michelin",
                                  "tirePosition": "RF",
                                  "tireCondition": "BLANK_CASE",
                                  "requestedAction": "REPLACE",
                                  "sculptedTreadName": "PILOT XFA"
                                }
                              ],
                              "requestedTires": [
                                {
                                  "asset": "#/data/attributes/primaryAsset",
                                  "axleType": "OTHER",
                                  "tireSize": "10.00/90R20",
                                  "loadRange": "L",
                                  "productType": "New",
                                  "manufacturer": "Michelin",
                                  "tirePosition": "RF",
                                  "tireCondition": "BLANK_CASE",
                                  "requestedAction": "REPLACE",
                                  "sculptedTreadName": "PILOT XFA"
                                }
                              ],
                              "specialInstructions": "",
                              "inboundProgramNumberId": 229,
                              "location_validated_by_driver_app": false
                            }
                          }
                        },
                        "createdAt": "2025-07-25T12:55:07.244Z",
                        "updatedAt": "2025-07-25T12:55:19.367Z",
                        "customerBillTo": "1424651"
                      },
                      {
                        "id": 40,
                        "caseId": "KBJPUUD6O5",
                        "ipn": null,
                        "customerShipTo": "1471852",
                        "ocxId": "E484101",
                        "fntId": null,
                        "fntCase": null,
                        "ocxCase": {
                          "data": {
                            "type": "ers-cases",
                            "warning": null,
                            "attributes": {
                              "contacts": [
                                {
                                  "name": "John",
                                  "type": "DRIVER_CELL",
                                  "phone": "9314090552",
                                  "callBackEta": false,
                                  "smsNotification": true,
                                  "callBackRollTime": false
                                },
                                {
                                  "name": "John",
                                  "type": "DISPATCH",
                                  "phone": "9314090552",
                                  "callBackEta": false,
                                  "smsNotification": true,
                                  "callBackRollTime": false
                                }
                              ],
                              "location": {
                                "zip": "29651",
                                "city": "Greer",
                                "note": "comment",
                                "state": "SC",
                                "country": "USA",
                                "highway": "",
                                "latitude": "34.9289684",
                                "timezone": "",
                                "longitude": "-82.2007266",
                                "mileMarker": "",
                                "searchValue": "202 GSP Logistic Parkway Greer, SC 29651 US",
                                "streetAddress": "202 GSP Logistic Parkway"
                              },
                              "agreedTires": [
                                {
                                  "asset": "#/data/attributes/primaryAsset",
                                  "axleType": "OTHER",
                                  "tireSize": "10.00/90R20",
                                  "loadRange": "L",
                                  "productType": "New",
                                  "manufacturer": "Michelin",
                                  "tirePosition": "RF",
                                  "requestedTire": "#/data/attributes/requestedTires/0",
                                  "tireCondition": "BLANK_CASE",
                                  "requestedAction": "REPLACE",
                                  "sculptedTreadName": "PILOT XFA"
                                }
                              ],
                              "billingInfo": {
                                "amount": "0.00",
                                "comment": "test",
                                "drNumber": "DR123204909",
                                "poNumber": "123",
                                "ticketNumber": "DR123204909",
                                "invoiceNumber": "345",
                                "referenceNumber": "ref12345"
                              },
                              "nafaCustomer": {
                                "billTo": "1424651",
                                "shipTo": "1471852"
                              },
                              "primaryAsset": {
                                "vin": null,
                                "type": "Tractor",
                                "unitNumber": "MT2626",
                                "droppedUnit": false
                              },
                              "relatedAssets": [],
                              "suppliedTires": [
                                {
                                  "asset": "#/data/attributes/primaryAsset",
                                  "axleType": "OTHER",
                                  "tireSize": "10.00/90R20",
                                  "loadRange": "L",
                                  "agreedTire": "#/data/attributes/agreedTires/0",
                                  "productType": "New",
                                  "manufacturer": "Michelin",
                                  "tirePosition": "RF",
                                  "tireCondition": "BLANK_CASE",
                                  "requestedAction": "REPLACE",
                                  "sculptedTreadName": "PILOT XFA"
                                }
                              ],
                              "requestedTires": [
                                {
                                  "asset": "#/data/attributes/primaryAsset",
                                  "axleType": "OTHER",
                                  "tireSize": "10.00/90R20",
                                  "loadRange": "L",
                                  "productType": "New",
                                  "manufacturer": "Michelin",
                                  "tirePosition": "RF",
                                  "tireCondition": "BLANK_CASE",
                                  "requestedAction": "REPLACE",
                                  "sculptedTreadName": "PILOT XFA"
                                }
                              ],
                              "specialInstructions": "",
                              "inboundProgramNumberId": 229,
                              "location_validated_by_driver_app": false
                            }
                          }
                        },
                        "createdAt": "2025-07-24T18:16:55.036Z",
                        "updatedAt": "2025-07-24T18:17:20.311Z",
                        "customerBillTo": "1424651"
                      }
                    ],
                    "total": 29
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "bearer": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/idp/v2/b2b/oauth2/token",
            "scopes": {}
          }
        }
      }
    }
  }
}